version: '3.8'

services:
  # Production service
  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: francoj22-portfolio-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Development service
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: francoj22-portfolio-dev
    ports:
      - "5174:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true